### ISSUE TITLE
Player avatars

### ISSUE THREAD

**Issue by Azurasky1** [Azurasky1/2dgame#15]
Configure logic such that the avatar size will scale depending on the resolution of the monitor
Each player avatar should be of uniform proportions

**Comment by Azurasky1** [comment]
What's the best way to do this?

**Comment by andreasonny83** [comment]
probably defining a scale ration and draw all the elements in the canvas according to that variable.
We will come back to this question in a second time.

**Comment by andreasonny83** [comment]
done in restyle
